# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: stehem.net
title: stehem's blog
author: Me
email: me@example.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
